#!/bin/bash
# Use - Script to turn start and stop the cal poly VPN                                           
# Auth - Srirag Vuppala                                                            
# ----------------------------------------------------------------------------  

#Enter in your Cal Poly Username and Password here
USERNAME=""
PASSWORD=""

connect() {
		echo -n "Started connection to Cal Poly VPN..."
		echo
		nohup openconnect --protocol=gp cpvpn.calpoly.edu --user=$USERNAME  --background --passwd-on-stdin <<< $PASSWORD > /dev/null & 
		echo
		echo -n "Connected!"
		echo
	}
disconnect() {
		echo -n "Disconnecting ..."
		echo
		killall -SIGINT openconnect
		echo
		echo -n "Disconnected! Have a nice day!"
	}


if [[ $EUID != 0 ]]; then
	echo "Only run this script as a sudo user"
	echo "USAGE: sudo cpvpn start|stop"
	exit 1
else
	if [[ $USERNAME == "" || $PASSWORD == "" ]]; then
		echo "Add in the Username and Password in the script"
		exit 2
	fi
	case "$1" in
		start)
			connect
			;;
		stop)
			disconnect
			;;
		*)
			echo "USAGE: sudo cpvpn start|stop"
			exit 3
			;;
	esac

fi
