#!/bin/bash
# Use - Script to turn start and stop the cal poly VPN                                           
# Auth - Srirag Vuppala                                                            
# ----------------------------------------------------------------------------  

#Enter in your Cal Poly Username and Password here
USERNAME=""
PASSWORD=""

PID=$(pidof openconnect) 

usage() {
	echo
	echo "USAGE: sudo cpvpn start|status|stop"
	echo
}


connect() {
		if [[ $PID == "" ]]; then
			echo -n "Started connection to Cal Poly VPN..."
			echo
			nohup openconnect --protocol=gp cpvpn.calpoly.edu --user=$USERNAME  --background --passwd-on-stdin <<< $PASSWORD > /dev/null & 
			echo
			echo -n "Connected!"
			echo
		else
			echo -n "Cal Poly VPN is already running "
			usage
		fi
	}
disconnect() {
		if [[ $PID != "" ]]; then
			echo -n "Disconnecting ..."
			echo
			killall -SIGINT openconnect
			killall -SIGINT openconnect
			kill $PID
			echo
			echo -n "Disconnected! Have a nice day!"
		else
			echo -n "Cal Poly VPN is not running"
			usage
		fi
	}

status_of_connection() {
#PID=$(pidof openconnect) 
		if [[ $PID != "" ]]; then
			echo "Cal Poly VPN is running! on PID - ${PID}"
		else
			echo "Cal Poly VPN is not running!"
		fi
	}

if [[ $EUID != 0 ]]; then
	echo "Only run this script as a sudo user"
	usage
	exit 1
else
	if [[ $USERNAME == "" || $PASSWORD == "" ]]; then
		echo "Add in the Username and Password in the script"
		exit 2
	fi
	case "$1" in
		start)
			connect
			;;
		status)
			status_of_connection
			;;
		stop)
			disconnect
			;;
		*)
			echo "USAGE: sudo cpvpn start|stop"
			exit 3
			;;
	esac

fi
